### ISSUE TITLE
Possibility of weather being undefined

### ISSUE THREAD

**Issue by jonnytest1** [CodingTrain/The-Weather-Here#4]
I got this stacktrace after opening the link on glitch.me

apparently item 20 (lat: 36.7231105 lon: -119.6896374) has no weather information which throws an error

logs.js:19 Uncaught (in promise) TypeError: Cannot read property 'summary' of undefined
    at getData (logs.js:19)
getData @ logs.js:19
async function (async)
getData @ logs.js:13
(anonymous) @ logs.js:10

**Comment by jonnytest1** [comment]
btw I created one marker that when clicked on makes the map more or less unusable ^^ #htmlInjection (dont worry script tags dont work)

**Comment by shiffman** [comment]
I think I've fixed this now, let me know if I'm mistaken!

**Comment by jonnytest1** [comment]
well the specific error in question doesnt seem to pop up but thats only because
```
Uncaught (in promise) TypeError: Cannot read property '0' of undefined
    at getData (logs.js:26)
```
this one comes first which also appears due to malformed data.
Why not try catch the entire inside of the for loop

oO you could also do some more validation in the backend to make sure all the fields are available

**Comment by jonnytest1** [comment]
https://github.com/CodingTrain/The-Weather-Here/pull/5
